import { Invoice, LineItem, CreditRequest, WorkflowConfig } from "./types";

export const invoices: Invoice[] = [
  {
    id: "INV-001",
    salesOrderId: 200100,
    salesOrderName: "Pandora - Carat - Q4 Holiday Be Love - Direct",
    primaryAdvertiserName: "Pandora",
    billingAccountName: "Carat",
    externalPoNumber: "O-4L6L1-R1",
    netInvoiceAmount: 2960100,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-002",
    salesOrderId: 200101,
    salesOrderName: "Nike - Mindshare - Q4 Holiday Sprint - Programmatic",
    primaryAdvertiserName: "Nike",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-5K7M2-R1",
    netInvoiceAmount: 5420000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-003",
    salesOrderId: 200102,
    salesOrderName: "Samsung - Starcom - CES 2025 Launch - Direct",
    primaryAdvertiserName: "Samsung",
    billingAccountName: "Starcom",
    externalPoNumber: "O-8R3N4-R1",
    netInvoiceAmount: 8750000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-004",
    salesOrderId: 200103,
    salesOrderName: "Apple - OMD - Back to School - Programmatic",
    primaryAdvertiserName: "Apple",
    billingAccountName: "OMD",
    externalPoNumber: "O-2J9P5-R1",
    netInvoiceAmount: 12300000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-005",
    salesOrderId: 200104,
    salesOrderName: "Amazon - Havas - Prime Day Push - Direct",
    primaryAdvertiserName: "Amazon",
    billingAccountName: "Havas",
    externalPoNumber: "O-6T1Q8-R1",
    netInvoiceAmount: 4100000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-006",
    salesOrderId: 200105,
    salesOrderName: "Toyota - Dentsu - Spring Campaign - Programmatic",
    primaryAdvertiserName: "Toyota",
    billingAccountName: "Dentsu",
    externalPoNumber: "O-3W5R7-R1",
    netInvoiceAmount: 6780000,
    reviewStatus: "Rejected",
    invoiceLockStatus: "unlocked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-007",
    salesOrderId: 200106,
    salesOrderName: "Microsoft - GroupM - Surface Launch - Direct",
    primaryAdvertiserName: "Microsoft",
    billingAccountName: "GroupM",
    externalPoNumber: "O-9A2S6-R1",
    netInvoiceAmount: 9500000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-008",
    salesOrderId: 200107,
    salesOrderName: "Coca-Cola - WPP - Holiday Cheer - Direct",
    primaryAdvertiserName: "Coca-Cola",
    billingAccountName: "WPP",
    externalPoNumber: "O-7B4D1-R1",
    netInvoiceAmount: 3200000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-009",
    salesOrderId: 200108,
    salesOrderName: "Meta - Publicis - Q1 Brand Safety - Programmatic",
    primaryAdvertiserName: "Meta",
    billingAccountName: "Publicis",
    externalPoNumber: "O-1C8F3-R1",
    netInvoiceAmount: 7600000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-010",
    salesOrderId: 200109,
    salesOrderName: "Pandora - Carat - Valentine's Day Push - Direct",
    primaryAdvertiserName: "Pandora",
    billingAccountName: "Carat",
    externalPoNumber: "O-4L6L1-R2",
    netInvoiceAmount: 1850000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-011",
    salesOrderId: 200110,
    salesOrderName: "BMW - PHD - Luxury Auto Q1 - Direct",
    primaryAdvertiserName: "BMW",
    billingAccountName: "PHD",
    externalPoNumber: "O-5H2K9-R1",
    netInvoiceAmount: 4450000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-012",
    salesOrderId: 200111,
    salesOrderName: "Unilever - Mindshare - Sustainability Campaign - Programmatic",
    primaryAdvertiserName: "Unilever",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-8P3Q7-R1",
    netInvoiceAmount: 5900000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-013",
    salesOrderId: 200112,
    salesOrderName: "Google - Essence - Pixel Launch - Direct",
    primaryAdvertiserName: "Google",
    billingAccountName: "Essence",
    externalPoNumber: "O-2M6N1-R1",
    netInvoiceAmount: 11200000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Lisa Park",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-014",
    salesOrderId: 200113,
    salesOrderName: "Nike - Mindshare - Summer Fitness - Programmatic",
    primaryAdvertiserName: "Nike",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-5K7M2-R2",
    netInvoiceAmount: 3350000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-015",
    salesOrderId: 200114,
    salesOrderName: "Amazon - Havas - Spring Deals - Direct",
    primaryAdvertiserName: "Amazon",
    billingAccountName: "Havas",
    externalPoNumber: "O-6T1Q8-R2",
    netInvoiceAmount: 6100000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-016",
    salesOrderId: 200115,
    salesOrderName: "L'Oreal - Publicis - Beauty Awards - Direct",
    primaryAdvertiserName: "L'Oreal",
    billingAccountName: "Publicis",
    externalPoNumber: "O-9D4E2-R1",
    netInvoiceAmount: 2780000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-017",
    salesOrderId: 200116,
    salesOrderName: "Samsung - Starcom - Galaxy S25 Launch - Direct",
    primaryAdvertiserName: "Samsung",
    billingAccountName: "Starcom",
    externalPoNumber: "O-8R3N4-R2",
    netInvoiceAmount: 14500000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-018",
    salesOrderId: 200117,
    salesOrderName: "Procter & Gamble - Carat - Super Bowl - Direct",
    primaryAdvertiserName: "Procter & Gamble",
    billingAccountName: "Carat",
    externalPoNumber: "O-1F7G5-R1",
    netInvoiceAmount: 22000000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-019",
    salesOrderId: 200118,
    salesOrderName: "Spotify - Dentsu - Wrapped Campaign - Programmatic",
    primaryAdvertiserName: "Spotify",
    billingAccountName: "Dentsu",
    externalPoNumber: "O-3X9Y1-R1",
    netInvoiceAmount: 1950000,
    reviewStatus: "Rejected",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-020",
    salesOrderId: 200119,
    salesOrderName: "Tesla - in-house - Cybertruck - Direct",
    primaryAdvertiserName: "Tesla",
    billingAccountName: "Tesla In-House",
    externalPoNumber: "O-4Z2A8-R1",
    netInvoiceAmount: 8900000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "December-2024",
  },
];

export const lineItemsByInvoice: Record<string, LineItem[]> = {
  "INV-001": [
    { lineItemId: "LI-001-A", lineItemName: "Holiday Be Love - Display 300x250", product: "Display Standard", netAmount: 1200000, grossAmount: 1440000 },
    { lineItemId: "LI-001-B", lineItemName: "Holiday Be Love - Display 728x90", product: "Display Standard", netAmount: 860100, grossAmount: 1032120 },
    { lineItemId: "LI-001-C", lineItemName: "Holiday Be Love - Native Content", product: "Native Article", netAmount: 900000, grossAmount: 1080000 },
  ],
  "INV-002": [
    { lineItemId: "LI-002-A", lineItemName: "Holiday Sprint - Programmatic Display", product: "Programmatic Display", netAmount: 2200000, grossAmount: 2640000 },
    { lineItemId: "LI-002-B", lineItemName: "Holiday Sprint - Programmatic Video", product: "Programmatic Video", netAmount: 3220000, grossAmount: 3864000 },
  ],
  "INV-003": [
    { lineItemId: "LI-003-A", lineItemName: "CES Launch - Takeover Package", product: "Homepage Takeover", netAmount: 4500000, grossAmount: 5400000 },
    { lineItemId: "LI-003-B", lineItemName: "CES Launch - Video Pre-roll", product: "Video Pre-roll", netAmount: 2500000, grossAmount: 3000000 },
    { lineItemId: "LI-003-C", lineItemName: "CES Launch - Newsletter Sponsorship", product: "Newsletter", netAmount: 1750000, grossAmount: 2100000 },
  ],
  "INV-004": [
    { lineItemId: "LI-004-A", lineItemName: "Back to School - Programmatic Display", product: "Programmatic Display", netAmount: 5000000, grossAmount: 6000000 },
    { lineItemId: "LI-004-B", lineItemName: "Back to School - Programmatic Native", product: "Programmatic Native", netAmount: 4500000, grossAmount: 5400000 },
    { lineItemId: "LI-004-C", lineItemName: "Back to School - Social Amplification", product: "Social", netAmount: 2800000, grossAmount: 3360000 },
  ],
  "INV-005": [
    { lineItemId: "LI-005-A", lineItemName: "Prime Day - Display ROS", product: "Display Standard", netAmount: 1500000, grossAmount: 1800000 },
    { lineItemId: "LI-005-B", lineItemName: "Prime Day - Sponsored Content", product: "Sponsored Content", netAmount: 2600000, grossAmount: 3120000 },
  ],
  "INV-006": [
    { lineItemId: "LI-006-A", lineItemName: "Spring Campaign - Programmatic Display", product: "Programmatic Display", netAmount: 3000000, grossAmount: 3600000 },
    { lineItemId: "LI-006-B", lineItemName: "Spring Campaign - Programmatic Video", product: "Programmatic Video", netAmount: 2280000, grossAmount: 2736000 },
    { lineItemId: "LI-006-C", lineItemName: "Spring Campaign - Audience Extension", product: "Audience Extension", netAmount: 1500000, grossAmount: 1800000 },
  ],
  "INV-007": [
    { lineItemId: "LI-007-A", lineItemName: "Surface Launch - Homepage Takeover", product: "Homepage Takeover", netAmount: 5000000, grossAmount: 6000000 },
    { lineItemId: "LI-007-B", lineItemName: "Surface Launch - Video Suite", product: "Video Pre-roll", netAmount: 4500000, grossAmount: 5400000 },
  ],
  "INV-008": [
    { lineItemId: "LI-008-A", lineItemName: "Holiday Cheer - Display 300x600", product: "Display Standard", netAmount: 1200000, grossAmount: 1440000 },
    { lineItemId: "LI-008-B", lineItemName: "Holiday Cheer - Native Placement", product: "Native Article", netAmount: 1000000, grossAmount: 1200000 },
    { lineItemId: "LI-008-C", lineItemName: "Holiday Cheer - Newsletter", product: "Newsletter", netAmount: 1000000, grossAmount: 1200000 },
  ],
  "INV-009": [
    { lineItemId: "LI-009-A", lineItemName: "Brand Safety - Programmatic Display", product: "Programmatic Display", netAmount: 4100000, grossAmount: 4920000 },
    { lineItemId: "LI-009-B", lineItemName: "Brand Safety - Programmatic Video", product: "Programmatic Video", netAmount: 3500000, grossAmount: 4200000 },
  ],
  "INV-010": [
    { lineItemId: "LI-010-A", lineItemName: "Valentine's Day - Display Package", product: "Display Standard", netAmount: 850000, grossAmount: 1020000 },
    { lineItemId: "LI-010-B", lineItemName: "Valentine's Day - Sponsored Content", product: "Sponsored Content", netAmount: 1000000, grossAmount: 1200000 },
  ],
  "INV-011": [
    { lineItemId: "LI-011-A", lineItemName: "Luxury Auto Q1 - Display Premium", product: "Display Premium", netAmount: 2000000, grossAmount: 2400000 },
    { lineItemId: "LI-011-B", lineItemName: "Luxury Auto Q1 - Video Pre-roll", product: "Video Pre-roll", netAmount: 1500000, grossAmount: 1800000 },
    { lineItemId: "LI-011-C", lineItemName: "Luxury Auto Q1 - Native Content", product: "Native Article", netAmount: 950000, grossAmount: 1140000 },
  ],
  "INV-012": [
    { lineItemId: "LI-012-A", lineItemName: "Sustainability - Programmatic Display", product: "Programmatic Display", netAmount: 3400000, grossAmount: 4080000 },
    { lineItemId: "LI-012-B", lineItemName: "Sustainability - Programmatic Native", product: "Programmatic Native", netAmount: 2500000, grossAmount: 3000000 },
  ],
  "INV-013": [
    { lineItemId: "LI-013-A", lineItemName: "Pixel Launch - Takeover", product: "Homepage Takeover", netAmount: 5500000, grossAmount: 6600000 },
    { lineItemId: "LI-013-B", lineItemName: "Pixel Launch - Video Suite", product: "Video Pre-roll", netAmount: 3200000, grossAmount: 3840000 },
    { lineItemId: "LI-013-C", lineItemName: "Pixel Launch - Newsletter Blast", product: "Newsletter", netAmount: 2500000, grossAmount: 3000000 },
  ],
  "INV-014": [
    { lineItemId: "LI-014-A", lineItemName: "Summer Fitness - Programmatic Display", product: "Programmatic Display", netAmount: 1850000, grossAmount: 2220000 },
    { lineItemId: "LI-014-B", lineItemName: "Summer Fitness - Programmatic Video", product: "Programmatic Video", netAmount: 1500000, grossAmount: 1800000 },
  ],
  "INV-015": [
    { lineItemId: "LI-015-A", lineItemName: "Spring Deals - Display ROS", product: "Display Standard", netAmount: 2500000, grossAmount: 3000000 },
    { lineItemId: "LI-015-B", lineItemName: "Spring Deals - Sponsored Content", product: "Sponsored Content", netAmount: 2100000, grossAmount: 2520000 },
    { lineItemId: "LI-015-C", lineItemName: "Spring Deals - Social", product: "Social", netAmount: 1500000, grossAmount: 1800000 },
  ],
  "INV-016": [
    { lineItemId: "LI-016-A", lineItemName: "Beauty Awards - Display Premium", product: "Display Premium", netAmount: 1280000, grossAmount: 1536000 },
    { lineItemId: "LI-016-B", lineItemName: "Beauty Awards - Video", product: "Video Pre-roll", netAmount: 1500000, grossAmount: 1800000 },
  ],
  "INV-017": [
    { lineItemId: "LI-017-A", lineItemName: "Galaxy S25 - Takeover Package", product: "Homepage Takeover", netAmount: 6000000, grossAmount: 7200000 },
    { lineItemId: "LI-017-B", lineItemName: "Galaxy S25 - Video Pre-roll", product: "Video Pre-roll", netAmount: 4500000, grossAmount: 5400000 },
    { lineItemId: "LI-017-C", lineItemName: "Galaxy S25 - Native Reviews", product: "Native Article", netAmount: 2500000, grossAmount: 3000000 },
    { lineItemId: "LI-017-D", lineItemName: "Galaxy S25 - Newsletter", product: "Newsletter", netAmount: 1500000, grossAmount: 1800000 },
  ],
  "INV-018": [
    { lineItemId: "LI-018-A", lineItemName: "Super Bowl - Premium Takeover", product: "Homepage Takeover", netAmount: 10000000, grossAmount: 12000000 },
    { lineItemId: "LI-018-B", lineItemName: "Super Bowl - Video Package", product: "Video Pre-roll", netAmount: 7000000, grossAmount: 8400000 },
    { lineItemId: "LI-018-C", lineItemName: "Super Bowl - Social Amplification", product: "Social", netAmount: 5000000, grossAmount: 6000000 },
  ],
  "INV-019": [
    { lineItemId: "LI-019-A", lineItemName: "Wrapped Campaign - Programmatic Display", product: "Programmatic Display", netAmount: 950000, grossAmount: 1140000 },
    { lineItemId: "LI-019-B", lineItemName: "Wrapped Campaign - Programmatic Audio", product: "Programmatic Audio", netAmount: 1000000, grossAmount: 1200000 },
  ],
  "INV-020": [
    { lineItemId: "LI-020-A", lineItemName: "Cybertruck - Display Premium", product: "Display Premium", netAmount: 3500000, grossAmount: 4200000 },
    { lineItemId: "LI-020-B", lineItemName: "Cybertruck - Video Suite", product: "Video Pre-roll", netAmount: 3400000, grossAmount: 4080000 },
    { lineItemId: "LI-020-C", lineItemName: "Cybertruck - Sponsored Content", product: "Sponsored Content", netAmount: 2000000, grossAmount: 2400000 },
  ],
};

export const creditRequests: CreditRequest[] = [
  {
    id: "CR-001",
    invoiceId: "INV-001",
    salesOrderName: "Pandora - Carat - Q4 Holiday Be Love - Direct",
    advertiserName: "Pandora",
    creditAmount: 150000,
    reason: "Campaign underdelivered by 15% due to inventory shortage",
    status: "completed",
    createdAt: "2024-12-01T10:30:00Z",
    updatedAt: "2024-12-03T14:20:00Z",
    requestedBy: "Jane Smith",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567891",
  },
  {
    id: "CR-002",
    invoiceId: "INV-003",
    salesOrderName: "Samsung - Starcom - CES 2025 Launch - Direct",
    advertiserName: "Samsung",
    creditAmount: 500000,
    reason: "Incorrect rate card applied - should be Q4 rates not Q1",
    status: "in_progress",
    createdAt: "2024-12-10T09:15:00Z",
    updatedAt: "2024-12-11T11:00:00Z",
    requestedBy: "Tom Wilson",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567892",
  },
  {
    id: "CR-003",
    invoiceId: "INV-005",
    salesOrderName: "Amazon - Havas - Prime Day Push - Direct",
    advertiserName: "Amazon",
    creditAmount: 200000,
    reason: "Duplicate billing for same impressions across two line items",
    status: "pending",
    createdAt: "2024-12-15T16:45:00Z",
    updatedAt: "2024-12-15T16:45:00Z",
    requestedBy: "Jane Smith",
  },
  {
    id: "CR-004",
    invoiceId: "INV-006",
    salesOrderName: "Toyota - Dentsu - Spring Campaign - Programmatic",
    advertiserName: "Toyota",
    creditAmount: 340000,
    reason: "Client disputes viewability metrics - below guaranteed threshold",
    status: "rejected",
    createdAt: "2024-12-08T11:20:00Z",
    updatedAt: "2024-12-12T09:30:00Z",
    requestedBy: "Tom Wilson",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567893",
  },
  {
    id: "CR-005",
    invoiceId: "INV-009",
    salesOrderName: "Meta - Publicis - Q1 Brand Safety - Programmatic",
    advertiserName: "Meta",
    creditAmount: 380000,
    reason: "Campaign paused for 3 days due to brand safety violation - prorated credit",
    status: "pending",
    createdAt: "2024-12-18T14:00:00Z",
    updatedAt: "2024-12-18T14:00:00Z",
    requestedBy: "Lisa Park",
  },
];

export const workflowConfigs: WorkflowConfig[] = [
  {
    workflowId: "credit-revision",
    workflowName: "Credit Revision Request",
    team: "Client Success",
    asanaProjectGid: "1234567890",
    asanaAssigneeGid: "9876543210",
    notificationEmails: ["finance@futureplc.com"],
    formFields: [
      {
        fieldId: "credit_amount",
        type: "currency",
        label: "Credit Amount",
        required: true,
      },
      {
        fieldId: "reason",
        type: "textarea",
        label: "Reason",
        required: true,
      },
    ],
  },
];

export function getUniqueValues(field: keyof Invoice): string[] {
  const values = new Set(invoices.map((inv) => String(inv[field])));
  return Array.from(values).sort();
}
