import { Invoice, CreditRequest, WorkflowConfig } from "./types";

export const invoices: Invoice[] = [
  {
    id: "INV-001",
    salesOrderId: 200100,
    salesOrderName: "Pandora - Carat - Q4 Holiday Be Love - Direct",
    primaryAdvertiserName: "Pandora",
    billingAccountName: "Carat",
    externalPoNumber: "O-4L6L1-R1",
    netInvoiceAmount: 2960100,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-002",
    salesOrderId: 200101,
    salesOrderName: "Nike - Mindshare - Q4 Holiday Sprint - Programmatic",
    primaryAdvertiserName: "Nike",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-5K7M2-R1",
    netInvoiceAmount: 5420000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-003",
    salesOrderId: 200102,
    salesOrderName: "Samsung - Starcom - CES 2025 Launch - Direct",
    primaryAdvertiserName: "Samsung",
    billingAccountName: "Starcom",
    externalPoNumber: "O-8R3N4-R1",
    netInvoiceAmount: 8750000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-004",
    salesOrderId: 200103,
    salesOrderName: "Apple - OMD - Back to School - Programmatic",
    primaryAdvertiserName: "Apple",
    billingAccountName: "OMD",
    externalPoNumber: "O-2J9P5-R1",
    netInvoiceAmount: 12300000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-005",
    salesOrderId: 200104,
    salesOrderName: "Amazon - Havas - Prime Day Push - Direct",
    primaryAdvertiserName: "Amazon",
    billingAccountName: "Havas",
    externalPoNumber: "O-6T1Q8-R1",
    netInvoiceAmount: 4100000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-006",
    salesOrderId: 200105,
    salesOrderName: "Toyota - Dentsu - Spring Campaign - Programmatic",
    primaryAdvertiserName: "Toyota",
    billingAccountName: "Dentsu",
    externalPoNumber: "O-3W5R7-R1",
    netInvoiceAmount: 6780000,
    reviewStatus: "Rejected",
    invoiceLockStatus: "unlocked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-007",
    salesOrderId: 200106,
    salesOrderName: "Microsoft - GroupM - Surface Launch - Direct",
    primaryAdvertiserName: "Microsoft",
    billingAccountName: "GroupM",
    externalPoNumber: "O-9A2S6-R1",
    netInvoiceAmount: 9500000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-008",
    salesOrderId: 200107,
    salesOrderName: "Coca-Cola - WPP - Holiday Cheer - Direct",
    primaryAdvertiserName: "Coca-Cola",
    billingAccountName: "WPP",
    externalPoNumber: "O-7B4D1-R1",
    netInvoiceAmount: 3200000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-009",
    salesOrderId: 200108,
    salesOrderName: "Meta - Publicis - Q1 Brand Safety - Programmatic",
    primaryAdvertiserName: "Meta",
    billingAccountName: "Publicis",
    externalPoNumber: "O-1C8F3-R1",
    netInvoiceAmount: 7600000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-010",
    salesOrderId: 200109,
    salesOrderName: "Pandora - Carat - Valentine's Day Push - Direct",
    primaryAdvertiserName: "Pandora",
    billingAccountName: "Carat",
    externalPoNumber: "O-4L6L1-R2",
    netInvoiceAmount: 1850000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-011",
    salesOrderId: 200110,
    salesOrderName: "BMW - PHD - Luxury Auto Q1 - Direct",
    primaryAdvertiserName: "BMW",
    billingAccountName: "PHD",
    externalPoNumber: "O-5H2K9-R1",
    netInvoiceAmount: 4450000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-012",
    salesOrderId: 200111,
    salesOrderName: "Unilever - Mindshare - Sustainability Campaign - Programmatic",
    primaryAdvertiserName: "Unilever",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-8P3Q7-R1",
    netInvoiceAmount: 5900000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-013",
    salesOrderId: 200112,
    salesOrderName: "Google - Essence - Pixel Launch - Direct",
    primaryAdvertiserName: "Google",
    billingAccountName: "Essence",
    externalPoNumber: "O-2M6N1-R1",
    netInvoiceAmount: 11200000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Lisa Park",
    billingPeriodName: "October-2024",
  },
  {
    id: "INV-014",
    salesOrderId: 200113,
    salesOrderName: "Nike - Mindshare - Summer Fitness - Programmatic",
    primaryAdvertiserName: "Nike",
    billingAccountName: "Mindshare",
    externalPoNumber: "O-5K7M2-R2",
    netInvoiceAmount: 3350000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-015",
    salesOrderId: 200114,
    salesOrderName: "Amazon - Havas - Spring Deals - Direct",
    primaryAdvertiserName: "Amazon",
    billingAccountName: "Havas",
    externalPoNumber: "O-6T1Q8-R2",
    netInvoiceAmount: 6100000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-016",
    salesOrderId: 200115,
    salesOrderName: "L'Oreal - Publicis - Beauty Awards - Direct",
    primaryAdvertiserName: "L'Oreal",
    billingAccountName: "Publicis",
    externalPoNumber: "O-9D4E2-R1",
    netInvoiceAmount: 2780000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "November-2024",
  },
  {
    id: "INV-017",
    salesOrderId: 200116,
    salesOrderName: "Samsung - Starcom - Galaxy S25 Launch - Direct",
    primaryAdvertiserName: "Samsung",
    billingAccountName: "Starcom",
    externalPoNumber: "O-8R3N4-R2",
    netInvoiceAmount: 14500000,
    reviewStatus: "None",
    invoiceLockStatus: "unlocked",
    assignedTo: "Lisa Park",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-018",
    salesOrderId: 200117,
    salesOrderName: "Procter & Gamble - Carat - Super Bowl - Direct",
    primaryAdvertiserName: "Procter & Gamble",
    billingAccountName: "Carat",
    externalPoNumber: "O-1F7G5-R1",
    netInvoiceAmount: 22000000,
    reviewStatus: "Approved",
    invoiceLockStatus: "locked",
    assignedTo: "Sarah Chen",
    billingPeriodName: "January-2025",
  },
  {
    id: "INV-019",
    salesOrderId: 200118,
    salesOrderName: "Spotify - Dentsu - Wrapped Campaign - Programmatic",
    primaryAdvertiserName: "Spotify",
    billingAccountName: "Dentsu",
    externalPoNumber: "O-3X9Y1-R1",
    netInvoiceAmount: 1950000,
    reviewStatus: "Rejected",
    invoiceLockStatus: "unlocked",
    assignedTo: "Mike Johnson",
    billingPeriodName: "December-2024",
  },
  {
    id: "INV-020",
    salesOrderId: 200119,
    salesOrderName: "Tesla - in-house - Cybertruck - Direct",
    primaryAdvertiserName: "Tesla",
    billingAccountName: "Tesla In-House",
    externalPoNumber: "O-4Z2A8-R1",
    netInvoiceAmount: 8900000,
    reviewStatus: "Pending",
    invoiceLockStatus: "unlocked",
    assignedTo: "Dan Perlee",
    billingPeriodName: "December-2024",
  },
];

export const creditRequests: CreditRequest[] = [
  {
    id: "CR-001",
    invoiceId: "INV-001",
    salesOrderName: "Pandora - Carat - Q4 Holiday Be Love - Direct",
    advertiserName: "Pandora",
    creditAmount: 150000,
    reason: "Campaign underdelivered by 15% due to inventory shortage",
    status: "completed",
    createdAt: "2024-12-01T10:30:00Z",
    updatedAt: "2024-12-03T14:20:00Z",
    requestedBy: "Jane Smith",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567891",
  },
  {
    id: "CR-002",
    invoiceId: "INV-003",
    salesOrderName: "Samsung - Starcom - CES 2025 Launch - Direct",
    advertiserName: "Samsung",
    creditAmount: 500000,
    reason: "Incorrect rate card applied - should be Q4 rates not Q1",
    status: "in_progress",
    createdAt: "2024-12-10T09:15:00Z",
    updatedAt: "2024-12-11T11:00:00Z",
    requestedBy: "Tom Wilson",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567892",
  },
  {
    id: "CR-003",
    invoiceId: "INV-005",
    salesOrderName: "Amazon - Havas - Prime Day Push - Direct",
    advertiserName: "Amazon",
    creditAmount: 200000,
    reason: "Duplicate billing for same impressions across two line items",
    status: "pending",
    createdAt: "2024-12-15T16:45:00Z",
    updatedAt: "2024-12-15T16:45:00Z",
    requestedBy: "Jane Smith",
  },
  {
    id: "CR-004",
    invoiceId: "INV-006",
    salesOrderName: "Toyota - Dentsu - Spring Campaign - Programmatic",
    advertiserName: "Toyota",
    creditAmount: 340000,
    reason: "Client disputes viewability metrics - below guaranteed threshold",
    status: "rejected",
    createdAt: "2024-12-08T11:20:00Z",
    updatedAt: "2024-12-12T09:30:00Z",
    requestedBy: "Tom Wilson",
    asanaTaskUrl: "https://app.asana.com/0/1234567890/1234567893",
  },
  {
    id: "CR-005",
    invoiceId: "INV-009",
    salesOrderName: "Meta - Publicis - Q1 Brand Safety - Programmatic",
    advertiserName: "Meta",
    creditAmount: 380000,
    reason: "Campaign paused for 3 days due to brand safety violation - prorated credit",
    status: "pending",
    createdAt: "2024-12-18T14:00:00Z",
    updatedAt: "2024-12-18T14:00:00Z",
    requestedBy: "Lisa Park",
  },
];

export const workflowConfigs: WorkflowConfig[] = [
  {
    workflowId: "credit-revision",
    workflowName: "Credit Revision Request",
    team: "Client Success",
    asanaProjectGid: "1234567890",
    asanaAssigneeGid: "9876543210",
    notificationEmails: ["finance@futureplc.com"],
    formFields: [
      {
        fieldId: "credit_amount",
        type: "currency",
        label: "Credit Amount",
        required: true,
      },
      {
        fieldId: "reason",
        type: "textarea",
        label: "Reason",
        required: true,
      },
    ],
  },
];

export function getUniqueValues(field: keyof Invoice): string[] {
  const values = new Set(invoices.map((inv) => String(inv[field])));
  return Array.from(values).sort();
}
